name = "bypass-manifest-cloudflare"
main = "src/index.js"
compatibility_date = "2026-05-27"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1

# [[routes]]
# pattern = "bypass.example.com"
# custom_domain = true

[triggers]
crons = ["0 */6 * * *"]

[[kv_namespaces]]
binding = "Bypass_KV"
# id = ""

[vars]
GIT_REPOSITORY_URL = "" # https://git.net/project/{username}/{repository}
PUBLIC_BASE_URL = "https://bypass.andrewe.dev"
